
# Permalinks
#permalink: :categories/:year/:month/:day/:title:output_ext

# setup
title:               Peter S. Ferguson
tagline:             Astronomer
job:                 Research Associate
location:            UW Madison
department:          Department of Physics
paginate_path:       "_pages/projects/page:num/"
paginate:            5

# About/contact
author:
  name:              Peter S. Ferguson
  github:               psferguson
  email:             petersferguson@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

include:
  - pages
  - _data
  - _includes

# Custom vars
google_analytics_id: #UA-XXXX-Y


domain: peterferguson.space       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://peterferguson.space  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /psferguson/psferguson.github.io      # place folder name if the site is served in a subfolder